GET http://localhost:3000/random?start=10&end=30

###
GET http://localhost:3000/generate-person?properties=firstName,lastName,email

###
GET http://localhost:3000/analyze-string?input=Hello123!elias420()?